/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as WheelRouteImport } from './routes/wheel'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CouponsRouteImport } from './routes/coupons'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CataloguesRouteImport } from './routes/catalogues'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CataloguesIdRouteImport } from './routes/catalogues.$id'
import { Route as AdminPromotionsRouteImport } from './routes/admin.promotions'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminParticipantsRouteImport } from './routes/admin.participants'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCompetitionsRouteImport } from './routes/admin.competitions'
import { Route as AdminCataloguesRouteImport } from './routes/admin.catalogues'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const WheelRoute = WheelRouteImport.update({
  id: '/wheel',
  path: '/wheel',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsRoute = CouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CataloguesRoute = CataloguesRouteImport.update({
  id: '/catalogues',
  path: '/catalogues',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CataloguesIdRoute = CataloguesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CataloguesRoute,
} as any)
const AdminPromotionsRoute = AdminPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParticipantsRoute = AdminParticipantsRouteImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompetitionsRoute = AdminCompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCataloguesRoute = AdminCataloguesRouteImport.update({
  id: '/catalogues',
  path: '/catalogues',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalogues': typeof CataloguesRouteWithChildren
  '/contact': typeof ContactRoute
  '/coupons': typeof CouponsRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/promotions': typeof PromotionsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stores': typeof StoresRoute
  '/wheel': typeof WheelRoute
  '/wishlist': typeof WishlistRoute
  '/admin/catalogues': typeof AdminCataloguesRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/catalogues/$id': typeof CataloguesIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogues': typeof CataloguesRouteWithChildren
  '/contact': typeof ContactRoute
  '/coupons': typeof CouponsRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/promotions': typeof PromotionsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stores': typeof StoresRoute
  '/wheel': typeof WheelRoute
  '/wishlist': typeof WishlistRoute
  '/admin/catalogues': typeof AdminCataloguesRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/catalogues/$id': typeof CataloguesIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalogues': typeof CataloguesRouteWithChildren
  '/contact': typeof ContactRoute
  '/coupons': typeof CouponsRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/promotions': typeof PromotionsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stores': typeof StoresRoute
  '/wheel': typeof WheelRoute
  '/wishlist': typeof WishlistRoute
  '/admin/catalogues': typeof AdminCataloguesRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/catalogues/$id': typeof CataloguesIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catalogues'
    | '/contact'
    | '/coupons'
    | '/login'
    | '/products'
    | '/promotions'
    | '/sitemap.xml'
    | '/stores'
    | '/wheel'
    | '/wishlist'
    | '/admin/catalogues'
    | '/admin/competitions'
    | '/admin/coupons'
    | '/admin/participants'
    | '/admin/products'
    | '/admin/promotions'
    | '/catalogues/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogues'
    | '/contact'
    | '/coupons'
    | '/login'
    | '/products'
    | '/promotions'
    | '/sitemap.xml'
    | '/stores'
    | '/wheel'
    | '/wishlist'
    | '/admin/catalogues'
    | '/admin/competitions'
    | '/admin/coupons'
    | '/admin/participants'
    | '/admin/products'
    | '/admin/promotions'
    | '/catalogues/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catalogues'
    | '/contact'
    | '/coupons'
    | '/login'
    | '/products'
    | '/promotions'
    | '/sitemap.xml'
    | '/stores'
    | '/wheel'
    | '/wishlist'
    | '/admin/catalogues'
    | '/admin/competitions'
    | '/admin/coupons'
    | '/admin/participants'
    | '/admin/products'
    | '/admin/promotions'
    | '/catalogues/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CataloguesRoute: typeof CataloguesRouteWithChildren
  ContactRoute: typeof ContactRoute
  CouponsRoute: typeof CouponsRoute
  LoginRoute: typeof LoginRoute
  ProductsRoute: typeof ProductsRoute
  PromotionsRoute: typeof PromotionsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoresRoute: typeof StoresRoute
  WheelRoute: typeof WheelRoute
  WishlistRoute: typeof WishlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wheel': {
      id: '/wheel'
      path: '/wheel'
      fullPath: '/wheel'
      preLoaderRoute: typeof WheelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons': {
      id: '/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof CouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogues': {
      id: '/catalogues'
      path: '/catalogues'
      fullPath: '/catalogues'
      preLoaderRoute: typeof CataloguesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/catalogues/$id': {
      id: '/catalogues/$id'
      path: '/$id'
      fullPath: '/catalogues/$id'
      preLoaderRoute: typeof CataloguesIdRouteImport
      parentRoute: typeof CataloguesRoute
    }
    '/admin/promotions': {
      id: '/admin/promotions'
      path: '/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/participants': {
      id: '/admin/participants'
      path: '/participants'
      fullPath: '/admin/participants'
      preLoaderRoute: typeof AdminParticipantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/competitions': {
      id: '/admin/competitions'
      path: '/competitions'
      fullPath: '/admin/competitions'
      preLoaderRoute: typeof AdminCompetitionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogues': {
      id: '/admin/catalogues'
      path: '/catalogues'
      fullPath: '/admin/catalogues'
      preLoaderRoute: typeof AdminCataloguesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCataloguesRoute: typeof AdminCataloguesRoute
  AdminCompetitionsRoute: typeof AdminCompetitionsRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminParticipantsRoute: typeof AdminParticipantsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminPromotionsRoute: typeof AdminPromotionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCataloguesRoute: AdminCataloguesRoute,
  AdminCompetitionsRoute: AdminCompetitionsRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminParticipantsRoute: AdminParticipantsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminPromotionsRoute: AdminPromotionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CataloguesRouteChildren {
  CataloguesIdRoute: typeof CataloguesIdRoute
}

const CataloguesRouteChildren: CataloguesRouteChildren = {
  CataloguesIdRoute: CataloguesIdRoute,
}

const CataloguesRouteWithChildren = CataloguesRoute._addFileChildren(
  CataloguesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CataloguesRoute: CataloguesRouteWithChildren,
  ContactRoute: ContactRoute,
  CouponsRoute: CouponsRoute,
  LoginRoute: LoginRoute,
  ProductsRoute: ProductsRoute,
  PromotionsRoute: PromotionsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoresRoute: StoresRoute,
  WheelRoute: WheelRoute,
  WishlistRoute: WishlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
